### PR TITLE
basic wrapper to load /save mhs keywords values from/to disk.

### PR DESCRIPTION
**Pull request by alefur**

### CODE REVIEW

**Review by CraigLoomis — COMMENTED** [review]
I like the simplicity, and the fact that it is _not_ a cache.

Protect against `$PFS_INSTDATA_DIR` not being set when `persist()` is called: `/data` is likely to be writable.

`pfs_instdata` is pretty general: I'm a little worried about the top-level directory `$PFS_INSTDATA_DIR/data/` getting confusing. We will have a minimum of 28 files there just for SPS.  

Me, I'd add `loadKeys()` and `persistKeys()`, or some such mechanism for handling multiple keys atomically.

**Review by CraigLoomis — COMMENTED** [review]
Also: this is MHS-specific: should it be in tron_actorcore,  at least for now?

**Comment by alefur** [comment]
Well, there are also those read-only static methods, that can be used outside mhs world.

**Comment by alefur** [comment]
@CraigLoomis Can we close this ?
I have other pending tickets depending on this that I need to close.

**Comment by CraigLoomis** [comment]
Looks good to me.

**Pull request closed without merging**
