### PR TITLE
DAMD-146: add proposalId/obCode to the pfsDesign constructor

### PR DESCRIPTION
**Pull request by monodera**
just put empty arrays for a dummy pfsDesign.

### CODE REVIEW

**Comment by PaulPrice** [comment]
Please don't merge `master` into the ticket branch. Use `git rebase` instead.
Also, please try to keep to the "one feature = one commit" rule as much as possible. For more information, see [here](https://developer.lsst.io/work/flow.html#appendix-commit-organization-best-practices).

**Comment by monodera** [comment]
Sorry for my ignorance (I followed what GitHub suggested).  Should I go back to the commit #2573ecc and `git rebase -i master` ?

**Comment by PaulPrice** [comment]
I think that if you do a `git rebase -i origin/master` and start squashing together related changes, you'll find that the merge commit will disappear as empty.

**Comment by monodera** [comment]
I followed the same procedure as that made to `datamodel` to clean the commits.

**Pull request merged**
